"use client";

import * as React from "react";
import { AlertTriangle, CarFront, CircleHelp, IndianRupee, ListChecks, Loader2, Pencil, Plus, RefreshCw, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { VehicleSearchableSelect } from "@/components/vehicles/vehicle-searchable-select";
import { calculatePackagePriceMatrix, formatPackageMoney } from "@/lib/packages/pricing";
import { deletePackageChild, savePackageAdjustment, savePackageContent, savePackageFaq, savePackageVehicle, syncPackageContentDefaults } from "@/lib/packages/mutations";
import { getNetworkErrorMessage } from "@/lib/client/network-error";
import type { PackageContentItem, PackageContentType, PackageDetail, PackageFaq, PackagePriceAdjustment, PackageReferenceData, PackageVehicleOption } from "@/types/package";

type Editor={kind:"vehicle";value:PackageVehicleOption|null}|{kind:"content";value:PackageContentItem|null}|{kind:"faq";value:PackageFaq|null}|{kind:"adjustment";value:PackagePriceAdjustment|null}|null;

export function PackageCommercialManager({pkg,refs,canEdit,canManagePricing}:{pkg:PackageDetail;refs:PackageReferenceData;canEdit:boolean;canManagePricing:boolean}){
 const [editor,setEditor]=React.useState<Editor>(null),[busy,setBusy]=React.useState(false),[error,setError]=React.useState<string|null>(null);
 const matrix=React.useMemo(()=>calculatePackagePriceMatrix(pkg,refs),[pkg,refs]);
 async function remove(kind:"vehicle"|"content"|"faq"|"adjustment",id:string){if(!confirm("Delete this item?"))return;setBusy(true);setError(null);try{const result=await deletePackageChild(kind,id,pkg.id);if(!result.success)setError(result.error);}catch(e){setError(getNetworkErrorMessage(e));}finally{setBusy(false);}}
 async function syncDefaults(){if(!confirm("Sync the latest default content into this package? Customized items will be preserved."))return;setBusy(true);setError(null);try{const result=await syncPackageContentDefaults(pkg.id);if(!result.success)setError(result.error);}catch(e){setError(getNetworkErrorMessage(e));}finally{setBusy(false);}}
 const contentSections=Array.from(pkg.content.reduce((groups,item)=>{const key=`${item.item_type}:${item.section_title}`;const group=groups.get(key)??{type:item.item_type,title:item.section_title,items:[] as PackageContentItem[]};group.items.push(item);groups.set(key,group);return groups;},new Map<string,{type:PackageContentType;title:string;items:PackageContentItem[]}>()).values()).sort((a,b)=>(a.items[0]?.display_order??0)-(b.items[0]?.display_order??0));
 return <div id="package-commercial-pricing" className="scroll-mt-24 space-y-6">
  {error&&<p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}
  <section className="space-y-4 rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><PanelHead icon={CarFront} title="Vehicle passenger rules" description="Choose the vehicle combination and billable days for each passenger band." action={canEdit?<Button type="button" onClick={()=>setEditor({kind:"vehicle",value:null})}><Plus/>Add rule</Button>:null}/>
   <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{pkg.vehicles.map(x=><Card key={x.id} title={`${x.minimum_pax}–${x.maximum_pax} passengers`} description={`${x.quantity} × ${x.model?.name??x.category?.name??"vehicle"} · ${x.billable_days} days`} canEdit={canEdit} busy={busy} active={editor?.kind==="vehicle"&&editor.value?.id===x.id} onEdit={()=>setEditor({kind:"vehicle",value:x})} onDelete={()=>remove("vehicle",x.id)}/>)}{!pkg.vehicles.length&&<Empty text="No vehicle rules. Pricing will show a warning until passenger bands are configured."/>}</div>
   {editor?.kind==="vehicle"&&<VehicleEditor key={`vehicle-${editor.value?.id??"new"}`} pkg={pkg} refs={refs} value={editor.value} busy={busy} setBusy={setBusy} onClose={()=>setEditor(null)} onError={setError}/>} 
  </section>

  <section className="space-y-4 rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><PanelHead icon={ListChecks} title="Website content & policies" description="Editable template snapshots plus itinerary-generated inclusions shown on the website and future PDF." action={canEdit?<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={busy||!["draft","inactive"].includes(pkg.status)} title={["draft","inactive"].includes(pkg.status)?"Preserves customized rows":"Set the package to draft before syncing defaults"} onClick={syncDefaults}><RefreshCw/>Sync defaults</Button><Button type="button" onClick={()=>setEditor({kind:"content",value:null})}><Plus/>Add item</Button></div>:null}/>
   <div className="rounded-xl border bg-muted/20 p-3 text-xs text-muted-foreground">{pkg.content_template_version?`Template version ${pkg.content_template_version} · last synced ${pkg.content_synced_at?new Date(pkg.content_synced_at).toLocaleString("en-IN"):"not recorded"}`:"No default template snapshot is linked yet."} Dynamic hotel, meal, vehicle and included-activity rows update from the itinerary.</div>
   <div className="grid gap-4 lg:grid-cols-2">{contentSections.map(section=><div key={`${section.type}:${section.title}`} className="overflow-hidden rounded-xl border"><div className="flex items-center justify-between gap-2 border-b bg-muted/30 px-4 py-3"><h3 className="text-sm font-semibold">{section.title}</h3><span className="rounded-full border bg-background px-2 py-0.5 text-[10px] capitalize">{section.type.replace("_"," ")}</span></div><div className="divide-y">{section.items.sort((a,b)=>a.display_order-b.display_order).map(x=><Card key={x.id} title={x.content} description={[x.is_system_generated?"Auto-generated":x.source_template_item_id?"Default snapshot":"Manual",x.is_customized?"Customized":null].filter(Boolean).join(" · ")} canEdit={canEdit} busy={busy} active={editor?.kind==="content"&&editor.value?.id===x.id} onEdit={()=>setEditor({kind:"content",value:x})} onDelete={()=>remove("content",x.id)} compact/>)}</div></div>)}{!contentSections.length&&<Empty text="No website content. Sync the active defaults or add an item."/>}</div>
   {editor?.kind==="content"&&<ContentEditor key={`content-${editor.value?.id??"new"}`} pkg={pkg} value={editor.value} busy={busy} setBusy={setBusy} onClose={()=>setEditor(null)} onError={setError}/>} 
  </section>

  <section className="space-y-4 rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><PanelHead icon={CircleHelp} title="Frequently asked questions" description="Expandable answers for the customer package detail page." action={canEdit?<Button type="button" onClick={()=>setEditor({kind:"faq",value:null})}><Plus/>Add FAQ</Button>:null}/>
   <div className="space-y-2">{pkg.faqs.map((x,index)=><details key={x.id} className={`rounded-xl border transition-colors ${editor?.kind==="faq"&&editor.value?.id===x.id?"border-primary/50 bg-primary/[0.025] ring-2 ring-primary/10":""}`}><summary className="flex cursor-pointer items-center gap-3 p-4"><span className="grid h-7 w-7 place-items-center rounded-full bg-primary/10 text-xs font-semibold text-primary">{index+1}</span><b className="flex-1 text-sm">{x.question}</b>{canEdit&&<span className="flex gap-1" onClick={e=>e.preventDefault()}><Button type="button" size="icon-sm" variant="ghost" onClick={()=>setEditor({kind:"faq",value:x})}><Pencil/></Button><Button type="button" size="icon-sm" variant="ghost" disabled={busy} onClick={()=>remove("faq",x.id)}><Trash2 className="text-destructive"/></Button></span>}</summary><p className="border-t p-4 text-sm text-muted-foreground">{x.answer}</p></details>)}{!pkg.faqs.length&&<Empty text="No FAQs added."/>}</div>
   {editor?.kind==="faq"&&<FaqEditor key={`faq-${editor.value?.id??"new"}`} pkg={pkg} value={editor.value} busy={busy} setBusy={setBusy} onClose={()=>setEditor(null)} onError={setError}/>} 
  </section>

  <section className="space-y-4 rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><PanelHead icon={IndianRupee} title="Dynamic pricing preview" description="Live per-person price for 2–6 adults, calculated from selected hotels, included activities and vehicles." action={canManagePricing?<Button type="button" onClick={()=>setEditor({kind:"adjustment",value:null})}><Plus/>Pricing adjustment</Button>:null}/>
   <PriceTable matrix={matrix} categories={refs.hotel_categories}/>
   {pkg.price_adjustments.length>0&&<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{pkg.price_adjustments.map(x=>{const category=refs.hotel_categories.find(c=>c.id===x.hotel_category_id);return <Card key={x.id} title={category?.name??"Category"} description={`${x.markup_bps/100}% markup · ${formatPackageMoney(x.fixed_adjustment_paise)} fixed`} canEdit={canManagePricing} busy={busy} active={editor?.kind==="adjustment"&&editor.value?.id===x.id} onEdit={()=>setEditor({kind:"adjustment",value:x})} onDelete={()=>remove("adjustment",x.id)}/>;})}</div>}
   {editor?.kind==="adjustment"&&<AdjustmentEditor key={`adjustment-${editor.value?.id??"new"}`} pkg={pkg} refs={refs} value={editor.value} busy={busy} setBusy={setBusy} onClose={()=>setEditor(null)} onError={setError}/>} 
  </section>
 </div>;
}

function PanelHead({icon:Icon,title,description,action}:{icon:React.ComponentType<{className?:string}>;title:string;description:string;action:React.ReactNode}){return <div className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5"/></span><div><h2 className="font-semibold">{title}</h2><p className="text-sm text-muted-foreground">{description}</p></div></div>{action}</div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">{text}</div>}
function Card({title,description,canEdit,busy,active=false,onEdit,onDelete,compact=false}:{title:string;description?:string;canEdit:boolean;busy:boolean;active?:boolean;onEdit:()=>void;onDelete:()=>void;compact?:boolean}){return <div className={`flex items-center gap-3 transition-colors ${compact?"p-3":"rounded-xl border p-4"} ${active?"bg-primary/[0.07] ring-2 ring-inset ring-primary/20":""}`}><div className="min-w-0 flex-1"><p className="text-sm font-medium">{title}</p>{description&&<p className="mt-1 text-xs text-muted-foreground">{description}</p>}</div>{canEdit&&<><Button type="button" size="icon-sm" variant={active?"secondary":"ghost"} aria-expanded={active} onClick={onEdit}><Pencil/></Button><Button type="button" size="icon-sm" variant="ghost" disabled={busy} onClick={onDelete}><Trash2 className="text-destructive"/></Button></>}</div>}
function EditorShell({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
 const containerRef=React.useRef<HTMLDivElement>(null);
 const titleId=React.useId();
 React.useEffect(()=>{
  const frame=window.requestAnimationFrame(()=>{
   const container=containerRef.current;
   if(!container)return;
   const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
   container.scrollIntoView({behavior:reducedMotion?"auto":"smooth",block:"start"});
   const target=container.querySelector<HTMLElement>('input:not([type="hidden"]):not([disabled]), textarea:not([disabled]), select:not([disabled]), [role="combobox"]:not([aria-disabled="true"])');
   (target??container).focus({preventScroll:true});
  });
  return()=>window.cancelAnimationFrame(frame);
 },[]);
 return <div ref={containerRef} role="region" aria-labelledby={titleId} tabIndex={-1} className="scroll-mt-28 rounded-xl border-2 border-primary/50 bg-primary/[0.04] p-4 shadow-lg shadow-primary/10 ring-4 ring-primary/10 outline-none"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><span className="h-2 w-2 shrink-0 animate-pulse rounded-full bg-primary"/><h3 id={titleId} className="font-semibold">{title}</h3><span className="hidden rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-primary sm:inline">Open editor</span></div><Button type="button" variant="ghost" data-editor-cancel onClick={onClose}>Cancel</Button></div>{children}</div>;
}
function SaveButton({busy}:{busy:boolean}){return <Button type="submit" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<Save/>}Save</Button>}

function VehicleEditor({pkg,refs,value,busy,setBusy,onClose,onError}:{pkg:PackageDetail;refs:PackageReferenceData;value:PackageVehicleOption|null;busy:boolean;setBusy:(v:boolean)=>void;onClose:()=>void;onError:(v:string|null)=>void}){
 const [form,setForm]=React.useState({minimum_pax:String(value?.minimum_pax??1),maximum_pax:String(value?.maximum_pax??6),base_location_id:value?.base_location_id??pkg.start_location_id??"",vehicle_category_id:value?.vehicle_category_id??"",vehicle_model_id:value?.vehicle_model_id??"",vendor_id:value?.vendor_id??"",quantity:String(value?.quantity??1),billable_days:String(value?.billable_days??pkg.duration_days),notes:value?.notes??""});const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const models=refs.vehicle_models.filter(x=>!form.vehicle_category_id||x.category_id===form.vehicle_category_id),vendors=refs.vehicle_vendors.filter(x=>!form.base_location_id||x.base_location_id===form.base_location_id);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);onError(null);try{const result=await savePackageVehicle(value?.id??null,{package_id:pkg.id,minimum_pax:Number(form.minimum_pax),maximum_pax:Number(form.maximum_pax),base_location_id:form.base_location_id,vehicle_category_id:form.vehicle_category_id,vehicle_model_id:form.vehicle_model_id||null,vendor_id:form.vendor_id||null,quantity:Number(form.quantity),billable_days:Number(form.billable_days),notes:form.notes.trim()||null,display_order:value?.display_order??pkg.vehicles.length});if(!result.success){onError(result.error);return;}onClose();}catch(e){onError(getNetworkErrorMessage(e));}finally{setBusy(false);}}
 return <EditorShell title={value?"Edit vehicle rule":"Add vehicle rule"} onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="space-y-1 text-sm font-medium">Minimum pax<Input required type="number" min={1} max={100} value={form.minimum_pax} onChange={e=>set("minimum_pax",e.target.value)}/></label><label className="space-y-1 text-sm font-medium">Maximum pax<Input required type="number" min={1} max={100} value={form.maximum_pax} onChange={e=>set("maximum_pax",e.target.value)}/></label><VehicleSearchableSelect label="Base location" name="vehicle_base" value={form.base_location_id} options={refs.locations.map(x=>({value:x.id,label:x.name,description:x.destination?.name??undefined}))} onValueChange={v=>{set("base_location_id",v);set("vendor_id","");}} placeholder="Search location" required/><VehicleSearchableSelect label="Category" name="vehicle_category" value={form.vehicle_category_id} options={refs.vehicle_categories.map(x=>({value:x.id,label:x.name}))} onValueChange={v=>{set("vehicle_category_id",v);set("vehicle_model_id","");}} placeholder="Choose category" required/><VehicleSearchableSelect label="Model" name="vehicle_model" value={form.vehicle_model_id} options={models.map(x=>({value:x.id,label:x.name}))} onValueChange={v=>set("vehicle_model_id",v)} placeholder="Category default" emptyOptionLabel="Category default"/><VehicleSearchableSelect label="Vendor" name="vehicle_vendor" value={form.vendor_id} options={vendors.map(x=>({value:x.id,label:x.name}))} onValueChange={v=>set("vendor_id",v)} placeholder="Default vendor" emptyOptionLabel="Any vendor"/><label className="space-y-1 text-sm font-medium">Quantity<Input required type="number" min={1} max={20} value={form.quantity} onChange={e=>set("quantity",e.target.value)}/></label><label className="space-y-1 text-sm font-medium">Billable days<Input required type="number" min={1} max={pkg.duration_days} value={form.billable_days} onChange={e=>set("billable_days",e.target.value)}/></label><label className="space-y-1 text-sm font-medium sm:col-span-2 lg:col-span-4">Notes<Textarea value={form.notes} onChange={e=>set("notes",e.target.value)}/></label><div className="flex justify-end sm:col-span-2 lg:col-span-4"><SaveButton busy={busy}/></div></form></EditorShell>;
}

function ContentEditor({pkg,value,busy,setBusy,onClose,onError}:{pkg:PackageDetail;value:PackageContentItem|null;busy:boolean;setBusy:(v:boolean)=>void;onClose:()=>void;onError:(v:string|null)=>void}){const [type,setType]=React.useState<PackageContentType>(value?.item_type??"inclusion"),[title,setTitle]=React.useState(value?.section_title??"Tour Inclusions"),[content,setContent]=React.useState(value?.content??"");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);onError(null);try{const result=await savePackageContent(value?.id??null,{package_id:pkg.id,item_type:type,section_title:title,content,display_order:value?.display_order??pkg.content.filter(x=>x.item_type===type).length});if(!result.success){onError(result.error);return;}onClose();}catch(e){onError(getNetworkErrorMessage(e));}finally{setBusy(false);}}return <EditorShell title={value?"Edit content":"Add website content"} onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm font-medium">Type<select className="h-10 w-full rounded-lg border bg-background px-3" value={type} onChange={e=>setType(e.target.value as PackageContentType)}><option value="highlight">Highlight</option><option value="inclusion">Inclusion</option><option value="exclusion">Exclusion</option><option value="important_note">Important note</option><option value="terms">Terms & conditions</option><option value="cancellation">Cancellation</option><option value="reschedule">Reschedule</option><option value="value_promise">Value promise</option></select></label><label className="space-y-1 text-sm font-medium">Section title<Input required minLength={2} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="space-y-1 text-sm font-medium sm:col-span-2">Content<Textarea required maxLength={3000} className="min-h-24" value={content} onChange={e=>setContent(e.target.value)}/></label><div className="flex justify-end sm:col-span-2"><SaveButton busy={busy}/></div></form></EditorShell>}
function FaqEditor({pkg,value,busy,setBusy,onClose,onError}:{pkg:PackageDetail;value:PackageFaq|null;busy:boolean;setBusy:(v:boolean)=>void;onClose:()=>void;onError:(v:string|null)=>void}){const [question,setQuestion]=React.useState(value?.question??""),[answer,setAnswer]=React.useState(value?.answer??"");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);onError(null);try{const result=await savePackageFaq(value?.id??null,{package_id:pkg.id,question,answer,display_order:value?.display_order??pkg.faqs.length});if(!result.success){onError(result.error);return;}onClose();}catch(e){onError(getNetworkErrorMessage(e));}finally{setBusy(false);}}return <EditorShell title={value?"Edit FAQ":"Add FAQ"} onClose={onClose}><form onSubmit={submit} className="space-y-4"><label className="space-y-1 text-sm font-medium">Question<Input required minLength={3} maxLength={500} value={question} onChange={e=>setQuestion(e.target.value)}/></label><label className="space-y-1 text-sm font-medium">Answer<Textarea required minLength={3} maxLength={5000} className="min-h-28" value={answer} onChange={e=>setAnswer(e.target.value)}/></label><div className="flex justify-end"><SaveButton busy={busy}/></div></form></EditorShell>}
function AdjustmentEditor({pkg,refs,value,busy,setBusy,onClose,onError}:{pkg:PackageDetail;refs:PackageReferenceData;value:PackagePriceAdjustment|null;busy:boolean;setBusy:(v:boolean)=>void;onClose:()=>void;onError:(v:string|null)=>void}){const [categoryId,setCategoryId]=React.useState(value?.hotel_category_id??""),[markup,setMarkup]=React.useState(String((value?.markup_bps??0)/100)),[fixed,setFixed]=React.useState(String((value?.fixed_adjustment_paise??0)/100)),[rounding,setRounding]=React.useState(String((value?.rounding_multiple_paise??10000)/100)),[notes,setNotes]=React.useState(value?.notes??"");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);onError(null);try{const result=await savePackageAdjustment(value?.id??null,{package_id:pkg.id,hotel_category_id:categoryId,markup_bps:Math.round(Number(markup)*100),fixed_adjustment_paise:Math.round(Number(fixed)*100),rounding_multiple_paise:Math.round(Number(rounding)*100),notes:notes.trim()||null});if(!result.success){onError(result.error);return;}onClose();}catch(e){onError(getNetworkErrorMessage(e));}finally{setBusy(false);}}return <EditorShell title={value?"Edit pricing adjustment":"Add pricing adjustment"} onClose={onClose}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><VehicleSearchableSelect label="Hotel category" name="adjustment_category" value={categoryId} options={refs.hotel_categories.map(x=>({value:x.id,label:x.name}))} onValueChange={setCategoryId} placeholder="Choose category" required/><label className="space-y-1 text-sm font-medium">Markup %<Input required type="number" min={-100} max={1000} step="0.01" value={markup} onChange={e=>setMarkup(e.target.value)}/></label><label className="space-y-1 text-sm font-medium">Fixed adjustment ₹<Input required type="number" step="0.01" value={fixed} onChange={e=>setFixed(e.target.value)}/></label><label className="space-y-1 text-sm font-medium">Round up to ₹<Input required type="number" min={0.01} step="0.01" value={rounding} onChange={e=>setRounding(e.target.value)}/></label><label className="space-y-1 text-sm font-medium sm:col-span-2 lg:col-span-4">Internal notes<Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="flex justify-end sm:col-span-2 lg:col-span-4"><SaveButton busy={busy}/></div></form></EditorShell>}

function PriceTable({matrix,categories}:{matrix:ReturnType<typeof calculatePackagePriceMatrix>;categories:PackageReferenceData["hotel_categories"]}){const warningCount=new Set(matrix.flatMap(x=>x.warnings)).size;return <div className="space-y-3">{warningCount>0&&<div className="flex gap-2 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/><span>{warningCount} pricing dependency warning{warningCount===1?"":"s"}. Hover a price cell to inspect missing configuration.</span></div>}<div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[920px] text-sm"><thead className="bg-muted/40"><tr><th className="p-3 text-left">Guests</th>{categories.map(c=><th key={c.id} className="min-w-40 p-3 text-right">{c.name}</th>)}</tr></thead><tbody className="divide-y">{[2,3,4,5,6].map(pax=><tr key={pax}><th className="p-3 text-left align-top font-medium">{pax} PAX</th>{categories.map(category=>{const cell=matrix.find(x=>x.pax===pax&&x.categoryId===category.id);return <td key={category.id} className={`p-3 align-top text-right ${cell?.warnings.length?"bg-amber-50/60 dark:bg-amber-950/10":""}`} title={cell?.warnings.join("\n")}><b className="text-base">{cell?formatPackageMoney(cell.perPersonPaise):"—"}</b><span className="block text-[10px] text-muted-foreground">per person · group {cell?formatPackageMoney(cell.groupTotalPaise):"—"}</span>{cell&&<div className="mt-2 space-y-0.5 border-t pt-2 text-[10px] text-muted-foreground"><span className="flex justify-between gap-2"><span>Hotel</span><b className="font-medium text-foreground">{formatPackageMoney(cell.hotelPaise)}</b></span><span className="flex justify-between gap-2"><span>Activities</span><b className="font-medium text-foreground">{formatPackageMoney(cell.activityPaise)}</b></span><span className="flex justify-between gap-2"><span>Vehicle</span><b className="font-medium text-foreground">{formatPackageMoney(cell.vehiclePaise)}</b></span></div>}</td>})}</tr>)}</tbody></table></div></div>}
