// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import type { Metadata } from "next";
import {  JetBrains_Mono, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";


const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)} suppressHydrationWarning>
      <body className={`${geist.variable}  ${fontMono.variable} antialiased`}>
      <ThemeProvider attribute="class"  defaultTheme="light" enableSystem disableTransitionOnChange>
         

        {children}
       
      </ThemeProvider>
      </body>
    </html>
  );
}